### ISSUE TITLE
Stackoverflow in recursive call

### ISSUE THREAD

**Issue by GeneralDenmark** [d702e20/OnTheFlyATL#73]
To find this fault @jenrik used lldb on the atl-tracker for one of the 8 mexicans from pr #72 

This created a stackoverflow, that could be found using lldb;

```
    frame #14261: 0x000055555577aae4 atl-checker`_$LT$atl_checker..atl..dependencygraph..DeltaIterator$LT$G$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::hb2c170d3cb59ec00(self=0x00007ffff7991a70) at dependencygraph.rs:306:17
```

This is a recursive call to this.next, which loops for a couple of times (see frame in message above)

**Comment by NicEastvillage** [comment]
I found the cause. Due to [this error in the biggg standoff](https://github.com/d702e20/OnTheFlyATL/pull/72#discussion_r539924949), all 139.968 successor configurations are the same, which means the DeltaIterator will recurse 139.968 times in attempt to find one that is different in [line 306](https://github.com/d702e20/OnTheFlyATL/blob/master/src/atl/dependencygraph.rs#L306). I had really not seen that coming. I will fix it with a loop.
